### ISSUE TITLE
"import RNA"

### ISSUE THREAD

**Issue by Abhinav-Mittal** [moss-lab/ScanFold#3]
Hi,
What is "import RNA" package in line 25 of ScanFold-Scan?
Thanks,
Abhinav Mittal
University of Rochester Medical Center,
Biophysics and Biochemistry Department

**Comment by rjandr** [comment]
Hello Abhinav,

That will import ViennaRNA python bindings and allow the script to work. Check this link to see how you install that module on your system. 

https://www.tbi.univie.ac.at/RNA/documentation.html#install

And here is a thread discussing some potential troubleshooting/fixes:
https://www.biostars.org/p/102061/

Let me know if that helps?
